### ISSUE TITLE
Add instructions about where to get module keys

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/NALMS_Not_Another_LMS#4]
It would make things smoother if we spelled out exactly where to get the module "keys" (especially since they aren't always an exact match for the module title). I actually ended up getting them from the text file with the times, but I think it should be spelled out that it is the name of the module md file and not necessarily the title with underscores.

**Comment by drelliche** [comment]
Added with https://github.com/arcus/NALMS_Not_Another_LMS/commit/294659148b99552b43a8b5c429586f4f413604be
