### ISSUE TITLE
Last modules being left off of instruments

### ISSUE THREAD

**Issue by leemc-data-ed** [arcus/NALMS_Not_Another_LMS#5]
The last modules of each section are being left off of the zip files of the instruments. You can get around this by adding an empty line to the end of each sections markdown file... though this doesn't seem ideal.

**Comment by drelliche** [comment]
Leaving this stack exchange conversation on this issue here for future debugging: https://stackoverflow.com/questions/12916352/shell-script-read-missing-last-line

**Comment by drelliche** [comment]
@leemc-data-ed Great catch! I believe this is now fixed with https://github.com/arcus/NALMS_Not_Another_LMS/commit/4a1612947e81e9c552ed0d9243b3a1eede700b53 so I'm closing this issue :)
